@startuml
start
:maintschedulelist/
partition (\WorkloadService::loadSavedData) {
    partition (\WorkloadBaseService::_initUnit) {
        :\WorkloadBaseService::_initUnit;
        :\WorkloadDao::getUnitListByRun;
        :\AMSP_Units::getUnitsByRuns;
    }
}

stop
@enduml